### ISSUE TITLE
开发计划

### ISSUE THREAD

**Issue by Wizzercn** [Wizzercn/NutzShop#1]
NutzWk v3.0  纯净版
NutzWk v3.1  增加微信模块
NutzWk v3.2  增加CMS模块

NutzShop  计划在NutzWk v3.2的基础上开发商城功能。

**Comment by ipandage** [comment]
目前正在开发 NutzShop 吗？

**Comment by Wizzercn** [comment]
@ipandage 木有  搁置中   工作比较忙另外是还nutzwk4.0还没完成

**Comment by ipandage** [comment]
方不方便 加个qq 请教个问题  546657868

**Comment by Wizzercn** [comment]
@ipandage qun:68428921
